#!/bin/bash

# Generate a self-signed TLS certificate and import it into ACM.
# Run once per account. Add the output ARN to .env as ACM_CERTIFICATE_ARN.
#
# Usage: ./setup-tls.sh
#
# For production, replace with a proper ACM certificate:
#   - ACM public cert with DNS validation (free, auto-renewing)
#   - Or import your organization's CA-signed certificate

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# Source .env
if [ -f ".env" ]; then
    set -a
    source .env
    set +a
fi

AWS_PROFILE="${AWS_PROFILE:-default}"
AWS_REGION="${AWS_REGION:-us-east-1}"

# Check if already configured
if [ -n "$ACM_CERTIFICATE_ARN" ]; then
    echo -e "${GREEN}ACM_CERTIFICATE_ARN already set in .env${NC}"
    echo "  $ACM_CERTIFICATE_ARN"
    echo "  To regenerate, remove ACM_CERTIFICATE_ARN from .env and re-run."
    exit 0
fi

echo -e "${BLUE}Generating self-signed TLS certificate...${NC}"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

# Generate key + cert (valid 365 days)
openssl req -x509 -nodes -newkey rsa:2048 \
    -keyout "$TMPDIR/key.pem" \
    -out "$TMPDIR/cert.pem" \
    -days 365 \
    -subj "/CN=patchy.internal" \
    2>/dev/null

# Import into ACM
CERT_ARN=$(aws acm import-certificate \
    --certificate fileb://"$TMPDIR/cert.pem" \
    --private-key fileb://"$TMPDIR/key.pem" \
    --region "$AWS_REGION" \
    --profile "$AWS_PROFILE" \
    --tags Key=Name,Value=patch-automation-ui-self-signed \
    --query 'CertificateArn' \
    --output text)

echo -e "${GREEN}Certificate imported: $CERT_ARN${NC}"

# Append to .env if it exists
if [ -f ".env" ]; then
    echo "" >> .env
    echo "# TLS certificate for UI ALB (generated by setup-tls.sh)" >> .env
    echo "ACM_CERTIFICATE_ARN=$CERT_ARN" >> .env
    echo -e "${GREEN}Added ACM_CERTIFICATE_ARN to .env${NC}"
else
    echo ""
    echo "Add to your .env:"
    echo "  ACM_CERTIFICATE_ARN=$CERT_ARN"
fi

echo ""
echo -e "Next: ${BLUE}./deploy.sh ui${NC} to redeploy with HTTPS"
